### PR TITLE
Proxy support

### LINKED ISSUE #270: Update device agent to operate behind a proxy
### Acceptance criteria

- [x] Unit Tests
   - [x] no_proxy
   - [x] all_proxy
   - [x] http_proxy
   - [x] https_proxy
- [x] Manual tests behind a proxy for Windows
    - [x] Device Setup
        - [x] Web-ui setup method
        - [x] One Time Code setup method
        - [x] Provisioning Token
    - [x] NR 3.x
        - [x] Device Status updates
        - [x] Device Logs accessible
        - [x] Device Editor Tunnel
        - [x] Device Audit Logger (do a flow modification, should make an audit log entry)
        - [x] Grab a snapshot
        - [x] Apply a snapshot
        - [x] Restart from actions menu
        - [x] Project Link to/from an instance on staging
    - [x] NR 4.x
        - [x] Device Status updates
        - [x] Device Logs accessible
        - [x] Device Editor Tunnel
        - [x] Device Audit Logger (do a flow modification, should make an audit log entry)
        - [x] Grab a snapshot
        - [x] Apply a snapshot
        - [x] Restart from actions menu
        - [x] Project Link to/from an instance on staging
- [ ] Manual tests behind a proxy for Linux
    - [ ] Device Setup
        - [ ] Web-ui setup method
        - [ ] One Time Code setup method
        - [ ] Provisioning Token
    - [ ] NR 3.x
        - [ ] Device Status updates
        - [ ] Device Logs accessible
        - [ ] Device Editor Tunnel
        - [ ] Device Audit Logger (do a flow modification, should make an audit log entry)
        - [ ] Grab a snapshot
        - [ ] Apply a snapshot
        - [ ] Restart from actions menu
        - [ ] Project Link to/from an instance on staging
    - [ ] NR 4.x
        - [ ] Device Status updates
        - [ ] Device Logs accessible
        - [ ] Device Editor Tunnel 
        - [ ] Device Audit Logger (do a flow modification, should make an audit log entry)
        - [ ] Grab a snapshot
        - [ ] Apply a snapshot
        - [ ] Restart from actions menu
        - [ ] Project Link to/from an instance on staging

NOTES:
*1 operation should be carried out using `http(s)_proxy` and `all_proxy`
*2. `no_proxy` should bypass `all/http(s)_proxy` causing traffic to go direct

### PR DESCRIPTION
**Pull request by Steve-Mcl**
closes #270

## Description

* Updates Device Agent to work behind a HTTP proxy
  * updates agent manager for device setup (bootstrapping)
  * updates library access plugin (for Node-RED access to FF library)
  * updates the auth part we add to settings.js
  * updates audit logger (post requests for audit logging)
  * updates MQTT and HTTP parts of Device Editor tunnel
  * Supports `no_proxy` and `all_proxy` (comes free with `proxy-from-env`) 
* Passes `*_proxy` env vars through to Node-RED env
* Adds dep `http-proxy-agent`, `https-proxy-agent`  & `proxy-from-env`

### Notes
* Updates package.json to include runtime dependencies
   *  `http-proxy-agent` & `https-proxy-agent`  - the most popular and supported agents by a long way, used for both HTTP and MQTT(ws)
   * `proxy-from-env` - this determined if a proxy should be applied by inspecting the process env vars. This is the same package that `proxy-agent` uses (`proxy-agent` is the parent mono repo of   `http-proxy-agent` & `https-proxy-agent` )
   * `eslint-plugin-no-only-tests`
* Updates package.json to include dev dependencies
   * `proxy` - for testing MQTT comms via a proxy
   * `rewire` - used in 2 places. `rewire` replaces `require` and permits access to unreachable internals for unit testing
      *  `auditLogger/index_spec.js` - `auditLogger` only returns a function and was impossible to access internal `got` object for unit testing.
      * `template-settings_spec.js` - `template-settings` only returns the final settings object and was impossible to access internal `got` object for unit testing.
* Updates eslint to enable `no-only-tests`
   * This was missing and I accidentally pushed with .only in test.

### Tests added

```
  Test the AgentManager
    ✔ Should not extend got with proxies if env vars are not set
    Proxy Support
      ✔ Calls GOT with no agent when env vars are not set
      ✔ Calls GOT with an http agent when env var is set (provisionDevice)
      ✔ Calls GOT with an https agent when env var is set (provisionDevice)
      ✔ Calls GOT with an http agent when env var is set (quickConnectDevice)
      ✔ Calls GOT with an https agent when env var is set (quickConnectDevice)
      ✔ Calls GOT with an http agent when env var is set (_getDeviceInfo)
      ✔ Calls GOT with an https agent when env var is set (_getDeviceInfo)

  auditLogger
    ✔ should send log message to the logging URL (100ms)
    ✔ should ignore comms events and any .get events (39ms)
    ✔ should ignore auth events except auth.log events (38ms)
    ✔ should remove username and level properties from the log message
    Proxy support
      ✔ should not have a proxy if env vars are not set
      ✔ should use HTTP proxy agent if http_proxy environment variable is set
      ✔ should use HTTPS proxy agent if https_proxy environment variable is set

  HTTP Comms
    Proxy Support
      ✔ Creates the HTTP Comms Client
      ✔ Extends GOT with http proxy when env var is set
      ✔ Extends GOT with https proxy when env var is set

  Launcher
    ✔ Creates a new launcher instance (107ms)
    Proxy Support
      ✔ Passes proxy env vars to child process when set (83ms)

  MQTT Comms
    Proxy Support
      ✔ MQTT Comms Client does not set a proxy agent if process env does not contain proxy settings
      ✔ MQTT Comms Client has a HttpProxyAgent for ws connection
      ✔ MQTT Comms Client has a HttpsProxyAgent for wss connection
      ✔ MQTT Comms Client can connect with proxy (516ms)
      ✔ MQTT command gets a response when proxy is set (572ms)

  FFTeamLibraryPlugin
    ✔ should throw an error if projectID and applicationID are missing
    ✔ should throw an error if libraryID is missing
    ✔ should throw an error if token is missing
    Proxy support
      ✔ should create an instance with valid configuration and no proxy
      ✔ should extend got to use http proxy when env var http_proxy is set
      ✔ should extend got to use https proxy when env var https_proxy is set
      ✔ should extend got to use http & https proxies when env vars are set

  template-settings
    ✔ should load default settings
    ✔ should call got.get with the correct parameters when verifying token
    ✔ should cache the token verification result for subsequent calls within 30 seconds
    - should not cache invalid token
    - should return without hitting cache or API if the token is not valid
    - should return null for the users function
    - should return null for the authenticate function
    - should set the https options if provided
    - should set the httpStatic option if provided
    Proxy Support
      ✔ should not extend got when env vars http(s)_proxy are not set
      ✔ should extend got to use http proxy when env var http_proxy is set (3180ms)
      ✔ should extend got to use https proxy when env var https_proxy is set (3134ms)

  utils
    getWSProxyAgent
      ✔ should return null when there are no env vars set
      ✔ should not proxy any requests if they are excluded by no_local
      ✔ should return a HttpProxyAgent when http_proxy is set and the URL is ws://
      ✔ should return a HttpsProxyAgent when https_proxy is set and the URL is wss://
      ✔ should set http proxy options
      ✔ should set https proxy options
    getHTTPProxyAgent
      ✔ should return an agent object without any http or https proxy when env vars are not set
      ✔ should not proxy any requests if they are excluded by no_local
      ✔ should return an agent object with http property when http_proxy is set and no_proxy is not in scope
      ✔ should return an agent object with http property when http_proxy is set
      ✔ should return an agent object with https property when https_proxy is set
      ✔ should set http proxy options
      ✔ should set https proxy options


  51 passing (8s)
  6 pending
```

## Related Issue(s)

#270 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [x] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by Steve-Mcl** [comment]
Ben spoke up about possible environments where setting a proxy may be necessary for access to external resources but not the forge backend (and vice versa)

We discussed the implementation should be aware of the `no_proxy` env var or perhaps use separate env vars (e.g. ff_device_http_proxy).

Supporting `no_proxy` was determined to be the most obvious first choice since it does not need describing or documenting due to being a well known "thing".

Switching PR to draft while I evaluate the options.

**Comment by Steve-Mcl** [comment]
@hardillb this is now ready for local testing.

**Comment by hardillb** [comment]
@Steve-Mcl Are you still testing this, or does the "TLDR" header mean you've finished poking at it?

**Comment by hardillb** [comment]
Basic testing working well once I'd configured the proxy to do websockets properly for none secure traffic.

Had a problem with NR 3.1 as the http-request node appears to be doing some strange things (using CONNECT to access http as well as https sites so had to reconfig the proxy to allow this).

NR 3.0.2 has no http_proxy support, so this "broke" when I upgraded the device to 3.1.x might need to look at NR side of things a little. My best guess is that it's using a https proxy agent for everything.

**Review by hardillb — APPROVED** [review]

**Pull request merged**
