### PR TITLE
Implement deferred stop like nr-launcher

### PR DESCRIPTION
**Pull request by Steve-Mcl**
## Description

Implement a deferred stop as per nr-launcher

## Related Issue(s)

#227 

Also, potentially the cause of https://github.com/FlowFuse/nr-project-nodes/issues/62

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by knolleary** [comment]
@Steve-Mcl what's the connection to the Project Nodes issue?

For the Project Nodes issue, Rob was using the Modified Nodes deploy type to make changes. I don't believe restarting Node-RED had anything to do with it.

**Comment by knolleary** [comment]
Sorry - just caught up on the comments in the linked issue. I'm not certain. Both instances would be trying to listen on the same port and one will fail to start, so I don't see how that results in two copies of the flows running in parallel.

**Comment by hardillb** [comment]
This is something that required fixing as it was possible to fail to start due to the old version still being running, but as you say I don't think is the cause of Rob's issue

**Comment by hardillb** [comment]
I'm going to merge this, but as mentioned I don't think it's the cause of the nr-project-nodes problem

**Comment by Steve-Mcl** [comment]
@knolleary @hardillb right you are. Thanks for the cycles.

**Pull request merged**
